#include <iostream>

// Rule of zero, three, five
// https://en.cppreference.com/w/cpp/language/rule_of_three.html

class Complex {
public:
    Complex() 
    : m_real{0.f}
    , m_im{0.f} 
    {
        std::cout << "default ctor call\n";
    }

    Complex(float real, float im) 
    : m_real{real}
    , m_im{im} 
    {
        std::cout << "float, float ctor call\n";
    }

    // Will not compile!
    // Complex(Complex other) : m_real{other.m_real}, m_im{other.m_im} {}

    // Complex(const Complex& other) = delete;
    // Complex& operator=(const Complex& other) = delete;

    Complex(const Complex& other) = default;
    Complex& operator=(const Complex& other) = default;
    ~Complex() = default;

//    Complex(const Complex& other) 
//    : m_real{other.m_real}
//    , m_im{other.m_im} 
//    {
//        std::cout << "copy ctor call\n";
//    }
//
//    Complex& operator=(const Complex& other) {
//        std::cout << "assignment operator call\n";
//        m_real = other.m_real;
//        m_im = other.m_im;
//        return *this;
//    }

    float real() const { return m_real; }
    float im() const { return m_im; }

private:
    float m_real;
    float m_im;
    bool isValid_;

    void do_copy(const Complex& other) {
        isValid_ = other.isValid_;
    }
};

class MyType {
public:
    MyType() = default;
    ~MyType() = default;
    MyType& operator=(const MyType& ) = default;
    
private:
    std::string str_;
};

void example() {
    Complex c{1.f, 2.f};

    // It is not a copy - it is a constructor call!
    Complex not_a_copy = Complex{3.f, 4.f};

    // Call a copy constructor here
    Complex copy = c;

    Complex assign;
    // Call a operator= here
    assign = c;

    Complex assign2;
    assign2 = (assign = c);
}

int main() {
    example();
    return 0;
}

/*
    Default operators and constructors will be generated by the compiler
    if the programmer did not implement them.
*/